### ISSUE TITLE
an error message appears

### ISSUE THREAD

**Issue by wibur0620** [viperyl/ComfyUI-GCoNet-plus#1]
[ERROR] An error occurred while retrieving information for the 'GCovNetPlus' node.
Traceback (most recent call last):
  File "D:\AI\ComfyUI\server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\AI\ComfyUI\server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-GCoNet-plus\GCovNet_plus_node.py", line 71, in INPUT_TYPES
    "checkpoints": (checkpoints, {"default": checkpoints[0]}),
                                             ~~~~~~~~~~~^^^
IndexError: list index out of range


[comfyui.log](https://github.com/viperyl/ComfyUI-GCoNet-plus/files/14737645/comfyui.log)

**Comment by wibur0620** [comment]
Fixed, turns out I didn't download the model

**Comment by wibur0620** [comment]
A new error occurs
![image](https://github.com/viperyl/ComfyUI-GCoNet-plus/assets/131615326/ba8e9bdf-3830-4b7d-bf06-772d3c54e1b0)
[comfyui.log](https://github.com/viperyl/ComfyUI-GCoNet-plus/files/14737724/comfyui.log)

**Comment by viperyl** [comment]
will be fix later

**Comment by viperyl** [comment]
did you check the model file size and model file sha256, i guess the model file corruption lead thie since it is workable on my Linux machine
